[project]
name = "posttraining-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets==3.6.0",
    "huggingface-hub==0.33.0",
    "ipykernel>=7.1.0",
    "jinja2==3.1.2",
    "markupsafe==2.0.1",
    "numpy==1.26.4",
    "pandas==2.3.0",
    "pytest>=8.4.1",
    "tabulate==0.9.0",
    "torch==2.3.0",
    "transformers==4.52.4",
    "trl==0.14.0",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py310"
line-length = 120
indent-width = 4
extend-exclude = [".venv", "notebooks", "experiments"]

[tool.ruff.lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "UP",     # pyupgrade
    "ARG001", # unused arguments in functions
]
ignore = [
    "B008",   # do not perform function calls in argument defaults
    "W191",   # indentation contains tabs
    "B904",   # Allow raising exceptions without from e, for HTTPException
    "E501",
    "ARG001",
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports 'from __future__ import annotations'
keep-runtime-typing = true

[tool.mypy]
explicit_package_bases = true # Requires all __init__.py files in packages being checked to have correct import roots.
install_types = true # Automatically installs missing stub packages (types-...) for third-party libraries.
non_interactive = true # Disables prompts and interaction during type stub installation.
follow_untyped_imports = true # Allows mypy to follow and analyze modules without type hints.
plugins = ['pydantic.mypy'] # Activates the Pydantic mypy plugin, which improves type checking support for Pydantic models.
files = ["src", "tests"]
